export const courses = [
    {
        id: "quran-reading-nazra",
        title: "Quran Reading",
        subtitle: "Learn to read the Quran with proper pronunciation from scratch",
        description:
            "This comprehensive Nazra course takes you from learning Arabic letters all the way to fluent Quran recitation. Structured for absolute beginners, it covers letter recognition, joining letters, vowel marks (harakat), and Madd (elongation) rules. By the end you will read the Quran independently with confidence and correct pronunciation.",
        image: "/courses/Quran-Memorization.jpeg",
        price: "Free Trial",
        originalPrice: "$99",
        rating: 4.9,
        ratingCount: "3.2k",
        students: 1240,
        lessons: 32,
        duration: "3 Months",
        level: "Beginner",
        language: "English, Urdu",
        category: "Quran",
        features: [
            "Arabic letter recognition",
            "Joining letters & syllables",
            "Short & long vowels",
            "Madd elongation rules",
            "Tanween & Shaddah",
            "Waqf (stopping) signs",
            "Practical reading exercises",
            "Final assessment",
        ],
        instructor: {
            name: "Sheikh Abdullah Al-Rashid",
            role: "Quran Recitation Instructor",
            image: "https://images.unsplash.com/photo-1756699270875-91531b2df854?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            rating: 4.9,
            learners: "2,400",
        },
        lectures: 64,
        quizzes: 12,
        assessments: true,
    },
    {
        id: "tajweed-mastery",
        title: "Tajweed Course",
        enrollCourse: "Tajweed Rules",
        subtitle: "Perfect your Quranic recitation with advanced Tajweed rules",
        description:
            "Tajweed Mastery is a structured course covering all the essential and advanced rules of Tajweed — the science of proper Quran recitation. From Noon Sakinah and Meem Sakinah to Qalqalah and Ghunnah, each rule is taught with clear examples and practice exercises directly from the Quran. Earn your Tajweed certificate upon completion.",
        image: "/courses/tajweed.jpg",
        price: "Free Trial",
        originalPrice: "$79",
        rating: 4.8,
        ratingCount: "2.1k",
        students: 980,
        lessons: 48,
        duration: "4 Months",
        level: "Intermediate",
        language: "English",
        category: "Tajweed",
        features: [
            "Noon Sakinah & Tanween rules",
            "Meem Sakinah rules",
            "Madd categories in detail",
            "Qalqalah letters",
            "Heavy & light letters",
            "Ghunnah (nasalization)",
            "Waqf & Ibtida rules",
            "Certificate of completion",
        ],
        instructor: {
            name: "Ustadha Fatima Al-Zahra",
            role: "Tajweed Specialist",
            image: "https://images.unsplash.com/photo-1756699270875-91531b2df854?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            rating: 4.8,
            learners: "1,800",
        },
        lectures: 96,
        quizzes: 20,
        assessments: true,
    },
    {
        id: "quran-memorization",
        title: "Quran memorization",
        subtitle: "Memorize the Holy Quran with proven revision techniques",
        description:
            "Our flagship Hifz program combines time-tested memorization methods with modern learning strategies. Sheikh Muhammad Ibrahim guides you through a structured schedule of new memorization (sabaq), recent revision (sabqi), and old revision (manzil). Suitable for students of all ages who wish to embark on the blessed journey of becoming a Hafiz.",
        image: "/courses/Quran-Recitation.jpeg",
        price: "Free Trial",
        originalPrice: "$199",
        rating: 4.9,
        ratingCount: "1.5k",
        students: 620,
        lessons: 120,
        duration: "24 Months",
        level: "All Levels",
        language: "English, Arabic",
        category: "Hifz",
        features: [
            "Daily new memorization (sabaq)",
            "Recent revision (sabqi)",
            "Old revision (manzil)",
            "Listening & repetition drills",
            "Error correction sessions",
            "Progress tracking system",
            "Motivational coaching",
            "Ijazah preparation",
        ],
        instructor: {
            name: "Sheikh Muhammad Ibrahim",
            role: "Hifz Coach",
            image: "https://images.unsplash.com/photo-1756699270875-91531b2df854?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            rating: 4.9,
            learners: "1,200",
        },
        lectures: 240,
        quizzes: 0,
        assessments: true,
    },
    {
        id: "islamic-studies-fundamentals",
        title: "Islamic Studies",
        subtitle: "Build a strong foundation in Aqeedah, Fiqh, and Seerah",
        description:
            "This course provides a well-rounded introduction to core Islamic sciences. Ustadha Aisha Siddiqui covers the six pillars of faith (Aqeedah), essential worship rulings (Fiqh), the life of the Prophet ﷺ (Seerah), and good character (Akhlaq). Designed to give students both the knowledge and the practical tools to live a fulfilling Islamic life.",
        image: "/courses/islamic-studies.jpeg",
        price: "Free Trial",
        originalPrice: "$59",
        rating: 4.7,
        ratingCount: "2.8k",
        students: 2100,
        lessons: 40,
        duration: "4 Months",
        level: "Beginner",
        language: "English",
        category: "Islamic Studies",
        features: [
            "Pillars of Islam & Iman",
            "Taharah & Salah rulings",
            "Zakat, Sawm & Hajj basics",
            "Seerah of Prophet Muhammad ﷺ",
            "Islamic ethics & character",
            "Halal & Haram overview",
            "Du'a & Dhikr collection",
            "Interactive Q&A sessions",
        ],
        instructor: {
            name: "Ustadha Aisha Siddiqui",
            role: "Islamic Studies Mentor",
            image: "https://images.unsplash.com/photo-1619974168383-aa4f9c99d359?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            rating: 4.7,
            learners: "980",
        },
        lectures: 80,
        quizzes: 16,
        assessments: true,
    },
    {
        id: "arabic-for-quran",
        title: "Arabic Language",
        subtitle: "Understand the Quran directly in its original language",
        description:
            "Sheikh Omar Al-Farouqi's Arabic for Quran course is designed to take you from zero Arabic knowledge to understanding basic Quranic vocabulary and sentence structures. The curriculum focuses on the most frequently used Quranic root words, verb forms, and grammatical patterns — giving you the tools to grasp the meaning of what you recite every day.",
        image: "/courses/arabiclanguage.jpg",
        price: "Free Trial",
        originalPrice: "$89",
        rating: 4.8,
        ratingCount: "1.9k",
        students: 870,
        lessons: 56,
        duration: "6 Months",
        level: "Beginner",
        language: "English",
        category: "Arabic",
        features: [
            "Arabic alphabet mastery",
            "Top 300 Quranic root words",
            "Noun & verb forms",
            "Basic sentence structure",
            "Quranic grammar (Nahw)",
            "Sarf (morphology) intro",
            "Vocabulary flashcards",
            "Translation exercises",
        ],
        instructor: {
            name: "Sheikh Omar Al-Farouqi",
            role: "Arabic Language Instructor",
            image: "https://images.unsplash.com/photo-1619974168383-aa4f9c99d359?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            rating: 4.8,
            learners: "1,500",
        },
        lectures: 112,
        quizzes: 24,
        assessments: true,
    },
    {
        id: "quran-tafseer",
        title: "Quran Tafseer (Interpretation)",
        enrollCourse: "Quran Tafseer",
        subtitle: "Explore the deeper meaning and context of Quranic verses",
        description:
            "This Tafseer course guides students through selected Surahs with detailed explanation of meanings, historical context (Asbab al-Nuzul), linguistic nuances, and scholarly commentary. Drawing from classical Tafseer works, Ustadha Aisha Siddiqui makes the profound wisdom of the Quran accessible for the modern Muslim seeking deeper connection with Allah's words.",
        image: "/courses/tafseer.jpg",
        price: "Free Trial",
        originalPrice: "$119",
        rating: 4.9,
        ratingCount: "1.2k",
        students: 540,
        lessons: 64,
        duration: "6 Months",
        level: "Intermediate",
        language: "English",
        category: "Tafseer",
        features: [
            "Meaning & context of verses",
            "Asbab al-Nuzul (revelation context)",
            "Linguistic analysis",
            "Classical scholar commentary",
            "Juz Amma complete tafseer",
            "Selected Meccan & Medinan Surahs",
            "Thematic Quran study",
            "Written reflection assignments",
        ],
        instructor: {
            name: "Ustadha Aisha Siddiqui",
            role: "Islamic Studies Mentor",
            image: "https://images.unsplash.com/photo-1619974168383-aa4f9c99d359?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            rating: 4.7,
            learners: "980",
        },
        lectures: 128,
        quizzes: 18,
        assessments: true,
    }
]

export function getCourseById(id) {
    return courses.find((c) => c.id === id) || null
}
