export const instructors = [
    {
        id: "sheikh-abdullah-rashid",
        name: "Sheikh Abdullah Al-Rashid",
        role: "Quran Recitation Instructor",
        experience: "15 Years",
        students: "2.4K",
        totalCourses: 8,
        rating: 4.9,
        bio: "Sheikh Abdullah Al-Rashid is a renowned Quran recitation instructor with over 15 years of experience teaching students worldwide. Having memorized the Quran at the age of 12 and earned multiple Ijazah certifications, he specializes in helping students develop beautiful and accurate recitation through personalized guidance and a nurturing approach that builds confidence at every level.",
        image: "https://images.unsplash.com/photo-1756699270875-91531b2df854?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        fullImage: "https://images.unsplash.com/photo-1756699270875-91531b2df854?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        phone: "+1 (985) 000-0001",
        email: "sheikh.abdullah@gmail.com",
        address: "123 Islamic Center Blvd, New York, NY 10001",
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        qualifications: [
            "Hafiz of the Holy Quran (memorized at age 12)",
            "Ijazah in Hafs from Asim — chain traced to the Prophet (PBUH)",
            "B.A. in Islamic Studies, Islamic University of Madinah",
            "Diploma in Tajweed, Egyptian Institute of Quranic Sciences",
        ],
        career: [
            { period: "2020 – Present", title: "Senior Quran Instructor", org: "Al-Noor Islamic Academy, New York" },
            { period: "2015 – 2020", title: "Quran Teacher", org: "Masjid Al-Furqan, New Jersey" },
            { period: "2009 – 2015", title: "Hifz Program Coordinator", org: "Dar Al-Quran Institute, Chicago" },
        ],
    },
    {
        id: "ustadha-fatima-zahra",
        name: "Ustadha Fatima Al-Zahra",
        role: "Tajweed Specialist",
        experience: "10 Years",
        students: "1.8K",
        totalCourses: 5,
        rating: 4.8,
        bio: "Ustadha Fatima Al-Zahra is a dedicated Tajweed specialist who has been teaching the rules of Quranic recitation for over a decade. A graduate of Al-Azhar University in Quranic Sciences, she brings deep scholarly knowledge paired with a patient, supportive teaching style that has helped thousands of students master precise pronunciation and proper application of Tajweed rules.",
        image: "https://userphotos2.teacheron.com/1182701-67746.jpg",
        fullImage: "https://userphotos2.teacheron.com/1182701-67746.jpg",
        phone: "+1 (985) 000-0002",
        email: "ustadha.fatima@gmail.com",
        address: "123 Islamic Center Blvd, New York, NY 10001",
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        qualifications: [
            "B.A. in Quranic Sciences, Al-Azhar University, Cairo",
            "Ijazah in Tajweed with Sanad — certified by Al-Azhar",
            "Diploma in Arabic Language & Linguistics",
            "Certificate in Islamic Education Methodology",
        ],
        career: [
            { period: "2021 – Present", title: "Lead Tajweed Instructor", org: "Al-Huda Online Quran Academy" },
            { period: "2016 – 2021", title: "Tajweed Teacher", org: "Noor Al-Islam Centre, London" },
            { period: "2013 – 2016", title: "Arabic & Quran Tutor", org: "Islamic Cultural Institute, Cairo" },
        ],
    },
    {
        id: "sheikh-muhammad-ibrahim",
        name: "Sheikh Muhammad Ibrahim",
        role: "Hifz Coach",
        experience: "12 Years",
        students: "1.2K",
        totalCourses: 4,
        rating: 4.9,
        bio: "Sheikh Muhammad Ibrahim is a dedicated Hifz coach who has guided over 500 students to complete memorization of the Holy Quran across 12 years of teaching. His systematic approach combines structured revision schedules with motivational techniques, making the memorization journey achievable and spiritually fulfilling for students of all backgrounds and age groups.",
        image: "https://images.unsplash.com/photo-1737571642094-4ecc024a3540?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        fullImage: "https://images.unsplash.com/photo-1737571642094-4ecc024a3540?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        phone: "+1 (985) 000-0003",
        email: "sheikh.muhammad@gmail.com",
        address: "123 Islamic Center Blvd, New York, NY 10001",
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        qualifications: [
            "Hafiz of the Holy Quran with Ijazah (Sanad to the Prophet PBUH)",
            "B.A. in Shariah & Islamic Studies, International Islamic University",
            "Certificate in Hifz Instruction & Curriculum Development",
            "Trained in Child-Centered Memorization Techniques",
        ],
        career: [
            { period: "2019 – Present", title: "Head Hifz Coach", org: "Quran Memorization Academy, Toronto" },
            { period: "2014 – 2019", title: "Hifz Teacher", org: "Masjid Al-Taqwa, Detroit" },
            { period: "2011 – 2014", title: "Quran Instructor", org: "Al-Iman Islamic School, Houston" },
        ],
    },
    {
        id: "ustadha-aisha-siddiqui",
        name: "Ustadha Rogaina Siddiqui",
        role: "Islamic Studies Mentor",
        experience: "8 Years",
        students: "980",
        totalCourses: 6,
        rating: 4.7,
        bio: "Ustadha Rogaina Siddiqui brings 8 years of experience covering Fiqh, Seerah, and Aqeedah. A graduate of the Islamic University of Madinah, she makes complex Islamic concepts accessible and relevant to contemporary Muslim life. Her interactive class style fosters critical thinking and a deep, practical understanding of Islamic principles for students at every stage.",
        image: "/aisha.webp",
        fullImage: "/aisha.webp",
        phone: "+1 (985) 000-0004",
        email: "ustadha.aisha@gmail.com",
        address: "123 Islamic Center Blvd, New York, NY 10001",
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        qualifications: [
            "B.A. in Islamic Studies, Islamic University of Madinah",
            "Specialization in Fiqh, Seerah & Aqeedah",
            "Diploma in Contemporary Islamic Issues",
            "Certificate in Instructional Design for Islamic Education",
        ],
        career: [
            { period: "2022 – Present", title: "Islamic Studies Mentor", org: "Seekers of Knowledge Institute, New York" },
            { period: "2017 – 2022", title: "Islamic Studies Teacher", org: "Al-Furqan Academy, Chicago" },
            { period: "2015 – 2017", title: "Youth Programs Coordinator", org: "Islamic Society of North America" },
        ],
    },
    {
        id: "sheikh-omar-farouqi",
        name: "Sheikh Omar Al-Farouqi",
        role: "Arabic Language Instructor",
        experience: "14 Years",
        students: "1.5K",
        totalCourses: 7,
        rating: 4.8,
        bio: "Sheikh Omar Al-Farouqi is a native Arabic speaker and certified language instructor specializing in Classical and Modern Standard Arabic. Over 14 years he has developed innovative methods that help non-native speakers build the strong linguistic foundation essential for understanding the Quran in its original language, unlocking deeper meaning and connection with the text.",
        image: "https://images.unsplash.com/photo-1619974168383-aa4f9c99d359?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        fullImage: "https://images.unsplash.com/photo-1619974168383-aa4f9c99d359?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        phone: "+1 (985) 000-0005",
        email: "sheikh.omar@gmail.com",
        address: "123 Islamic Center Blvd, New York, NY 10001",
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        qualifications: [
            "B.A. in Arabic Language & Literature, Cairo University",
            "Ijazah in Classical Arabic Grammar (Nahw & Sarf)",
            "Certificate in Teaching Arabic as a Foreign Language (TAFL)",
            "Diploma in Quranic Arabic — Bayyinah Institute",
        ],
        career: [
            { period: "2018 – Present", title: "Classical Arabic Instructor", org: "Al-Madinah Arabic Institute, New York" },
            { period: "2013 – 2018", title: "Arabic Language Teacher", org: "Quranic Arabic Academy, Dallas" },
            { period: "2010 – 2013", title: "Arabic Tutor", org: "Islamic Cultural Center, Cairo" },
        ],
    },
    {
        id: "ustadha-khadija-hassan",
        name: "Ustadha Khadija Hassan",
        role: "Quran for Kids Specialist",
        experience: "9 Years",
        students: "750",
        totalCourses: 3,
        rating: 4.9,
        bio: "Ustadha Khadija Hassan specializes in early childhood Quran education for children aged 4–12. With 9 years of experience and certifications in both Islamic studies and child psychology, her playful yet structured teaching approach has helped hundreds of young learners build a strong Quranic foundation and a lifelong love for the words of Allah.",
        image: "https://images.unsplash.com/photo-1621982068749-d74c76e05720?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        fullImage: "https://images.unsplash.com/photo-1621982068749-d74c76e05720?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        phone: "+1 (985) 000-0006",
        email: "ustadji@gmail.com",
        address: "123 Islamic Center Blvd, New York, NY 10001",
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        qualifications: [
            "B.A. in Islamic Studies with Child Psychology Minor, International Islamic University",
            "Ijazah in Quran Recitation — certified instructor chain",
            "Certificate in Early Childhood Islamic Education",
            "Diploma in Child-Centered Teaching Methodologies",
        ],
        career: [
            { period: "2020 – Present", title: "Quran for Kids Lead Instructor", org: "Noor Kids Academy, New York" },
            { period: "2016 – 2020", title: "Children's Quran Teacher", org: "Masjid Al-Rahman, Los Angeles" },
            { period: "2014 – 2016", title: "Islamic Preschool Educator", org: "Crescent Moon Islamic School, Boston" },
        ],
    },
    {
        id: "sheikh-yusuf-mansour",
        name: "Sheikh Yusuf Al-Mansour",
        role: "Qira'at Specialist",
        experience: "11 Years",
        students: "1.1K",
        totalCourses: 6,
        rating: 4.8,
        bio: "Sheikh Yusuf Al-Mansour is an expert in the ten Qira'at (recitation modes) of the Holy Quran, with over 11 years of teaching experience. Trained under renowned scholars in Egypt, he helps advanced students explore the depth and beauty of the different narrations while maintaining a strong foundation in classical Tajweed principles.",
        image: "https://res.cloudinary.com/dlnnjkoes/image/upload/v1783612084/SAUDI_k9v0qc.png",
        fullImage: "https://res.cloudinary.com/dlnnjkoes/image/upload/v1783612084/SAUDI_k9v0qc.png",
        phone: "+1 (985) 000-0007",
        email: "sheikh.yusuf@gmail.com",
        address: "123 Islamic Center Blvd, New York, NY 10001",
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        qualifications: [
            "Ijazah in the Ten Qira'at — Al-Azhar Al-Sharif, Cairo",
            "B.A. in Quranic Studies, Al-Azhar University",
            "Advanced Certificate in Tajweed & Qira'at Theory",
            "Diploma in Quranic Recitation Pedagogy",
        ],
        career: [
            { period: "2021 – Present", title: "Qira'at Instructor", org: "Dar Al-Qira'at Institute, New York" },
            { period: "2016 – 2021", title: "Senior Recitation Teacher", org: "Al-Azhar Quran Academy, Cairo" },
            { period: "2012 – 2016", title: "Quran Teacher", org: "Masjid Al-Salam, Alexandria" },
        ],
    },
]

export function getInstructorById(id) {
    return instructors.find((i) => i.id === id) || null
}
